name: Prueba

on: push

jobs:
  notification-slack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Create JSON payload2 for Slack
      run: |
        echo '
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|[barberia-backend:prodiccion:actions-run]> new deploy by *${{ github.actor }}*\n\n"
                }
              },
              {
                "type": "rich_text",
                "elements": [
                  {
                    "type": "rich_text_quote",
                    "elements": [
                      {
                        "type": "text",
                        "text": "Despliegue subsecuente iniciado",
                        "style": {
                          "bold": true
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ' > payload-slack-content.json

    - name: Send custom event details to a Slack workflow
      id: slack-notification
      uses: slackapi/slack-github-action@v2.0.0
      with:
        payload-file-path: "./payload-slack-content.json"
        payload-templated: true
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: webhook-trigger
      # with:
      #   webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   webhook-type: incoming-webhook
      #   payload: |
      #     text: "*GitHub Action build result*: ${{ job.status }}"
      #     blocks:
      #       - type: "section"
      #         text:
      #           type: "mrkdwn"
      #           text: "GitHub Action build result: ${{ job.status }}"