name: Prueba

on: push

jobs:
  notification-slack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Send custom event details to a Slack workflow
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: webhook-trigger
        payload: |
          status: "${{ job.status }}"
          option: "true"